### PR TITLE
SQL Implementation

### PR DESCRIPTION
**Pull request by BLUE-DEVIL1134**
Soon implementing SQL feature!

### CODE REVIEW

**Comment by buddhhu** [comment]
@BLUE-DEVIL1134 Bete

**Comment by BLUE-DEVIL1134** [comment]
ik son !

**Comment by TechiError** [comment]
**NO SQL NEEDED** in ultroid

**Comment by New-dev0** [comment]
@TechiError Why?

**Comment by BLUE-DEVIL1134** [comment]
> **NO SQL NEEDED** in ultroid

bc go read sst for tuesday, dont duck here!

**Pull request closed without merging**
